version: '3.8'

services:
  redis:
    image: redis:6.0.9
    environment:
      - REDIS_PASSWORD=secret
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - ota-server
  ota-server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env
    command: reflex -r '\.go' -s -- sh -c "ls -l cmd/api && go run cmd/api/main.go"
